#!/usr/bin/env bash
# This script displays "Into the endless void" repeatedly,
# with a 2-second pause between each iteration.

trap 'echo "I am invincible!!!"' SIGTERM
while :
do
    echo "To infinity and beyond"
    sleep 2
done