#!/usr/bin/env bash
# This displays numbers from 1-100 fizzbuzz.

for number in {1..100}
do
    if [ $((number % 3)) == 0 ] && [ $((number % 5)) == 0 ]
    then
        echo "FizzBuzz"
    elif [ $((number % 5)) == 0 ]
    then
        echo "Buzz"
    elif [ $((number % 3)) == 0 ]
    then
        echo "Fizz"
    else
        echo "$number"
    fi
done
